version: '3.8'
name: weather-app
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=weather-app
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
  weather-application:
    image: altirel/weather-app-backend
    container_name: weather-app-backend
    build:
      context: weather-app-backend
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=weather-app
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - OPEN_WEATHER_VERSION=2.5
      - OPEN_WEATHER_API_KEY=${OPEN_WEATHER_API_KEY}
    ports:
      - '8081:8080'
    volumes:
      - application:/tmp
volumes:
  db:
    driver: local
  pgadmin:
    driver: local
  application:
    driver: local
    